# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - python3 -m pip install --upgrade setuptools
  - python3 setup.py -q install

# command to run tests, e.g. python setup.py test
script:
  - python3 setup.py pytest

